language: ruby
install:
    - bundle install
rvm:
    - 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: P99EIMrtXoDE9qkOe//AgovKqxIO28UVBpGfPSyuiEWBAvD9AKcbQQDGqQmoGDczv27Fp8zHqtTm5K3bhE8oX2E9Fuvjy/QtM5Che6JvTzPeANkJx8pLTHlXruiaDNtBNf/3a8zCqedOhOFb3TMaz3ka03PZtXA2GDRivGgfMTVQ3sBsEinUENKKqA0EKkY2d8QVTPQhGJvEUtTUFDZnnP67EvxjrL87ty3vO+ZyIBqDBrTIYTUcKrfcgRcfUOdHDb1oc6P3BzBfp2kKgHCZfKTzDnv+6cpQlataiQuld7KwzSrIfNNL7Fc2nkK7sF9S1fgeO/QGCYvIkDyTAx97WQys705AD42bREIDJzQPGVIp4SSmw4NkCJXxP9z95hR11Bpt0+aV2EksSzDZ8ye5iaBWVUpKoU5/QtwQRTrRuI2UULd5KZrf1j1d3raiIbqbnLis36pP5jh9mguHojcSR/Csuc7v9rpKkkKogTsDN2epvI0ME7B7a/Jj76YxtbTU3xFnYdQn0yLAoPAQdf8nEWW8vjD8pGVvTeltcJGo/m6CGEe0wA64ve3kJtITZFPV2Qfn/KVgPvKK2jic5WjNasJefzLjNhtZsBsFRfxGyCLFdz6hNsr7QcfFH6CcN1RtKmSPAcWfUnzUCvOht8vjC5B797lUlyMt1MRF2ssyp8U=
